[tool.pytest.ini_options]
testpaths = ["tests/server/"]
python_classes = []
asyncio_mode = "auto"
markers = [
  "online: test has online dependencies",
]

[tool.black]
  line-length = 119
  target-version = ['py39']
  extend-exclude = '''
  ^/(
      env/
    | tests/server/data/user_scripts/
    | tests/azmlinfsrv/resources/
  )
  '''

[tool.towncrier]
  package = "azureml_inference_server_http"
  package_dir = ""
  filename = "CHANGELOG.rst"
  directory = "changes/"
  title_format = "{version} ({project_date})"
  template = "changes/_template.rst"
  underlines = ["~", "-", "^"]

  [[tool.towncrier.type]]
      directory = "breaking"
      name = "Breaking Changes"
      showcontent = true

  [[tool.towncrier.type]]
      directory = "feature"
      name = "Features"
      showcontent = true

  [[tool.towncrier.type]]
      directory = "enhancement"
      name = "Enhancements"
      showcontent = true

  [[tool.towncrier.type]]
      directory = "fix"
      name = "Fixes"
      showcontent = true
