name: test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: src/azureml-inference-server-http/

jobs:
  Common-Server-CI:
    strategy:
      matrix:
        python_version: ['3.7', '3.8', '3.9', '3.10']
        pool_vmImage: ['ubuntu-latest', 'windows-latest']
    runs-on: ${{matrix.pool_vmImage}}

    steps:
    
      - name: Clone branch
        uses: actions/checkout@v3

      # Specify the python version
      - name: Set Python Version
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python_version}}

      - name: Install azureml_inference_server_http
        run: |
            pip install -e .[dev]
      
      - name: Run Tests
        run: |
            set -e
            pip install pytest-azurepipelines
            coverage run --rcfile tests/server/.coveragerc -m \
            pytest \
              --no-coverage-upload
            coverage combine . tests/server
            # Ignore errors because it won't be able to find the `main.py` that was temporary placed into the package.
            coverage report --ignore-errors --show-missing
            coverage xml --ignore-errors
